// <auto-generated />
using System;
using Econyx.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Econyx.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(EconyxDbContext))]
    [Migration("20260310225309_AddApiKeyConfiguration")]
    partial class AddApiKeyConfiguration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Econyx.Domain.Entities.AiModelConfiguration", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("CompletionPricePer1M")
                        .HasPrecision(18, 8)
                        .HasColumnType("decimal(18,8)");

                    b.Property<int>("ContextLength")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<int>("MaxTokens")
                        .HasColumnType("int");

                    b.Property<string>("ModelId")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<decimal>("PromptPricePer1M")
                        .HasPrecision(18, 8)
                        .HasColumnType("decimal(18,8)");

                    b.Property<string>("Provider")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("IsActive");

                    b.HasIndex("Provider", "ModelId");

                    b.ToTable("AiModelConfigurations", (string)null);
                });

            modelBuilder.Entity("Econyx.Domain.Entities.ApiKeyConfiguration", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("EncryptedKey")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<bool>("IsConfigured")
                        .HasColumnType("bit");

                    b.Property<string>("MaskedDisplay")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Provider")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("Provider")
                        .IsUnique();

                    b.ToTable("ApiKeyConfigurations", (string)null);
                });

            modelBuilder.Entity("Econyx.Domain.Entities.BalanceSnapshot", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Mode")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int>("OpenPositionCount")
                        .HasColumnType("int");

                    b.Property<decimal>("TotalPnLPercent")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)");

                    b.Property<int>("TotalTrades")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("WinRate")
                        .HasPrecision(5, 4)
                        .HasColumnType("decimal(5,4)");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAt");

                    b.ToTable("BalanceSnapshots", (string)null);
                });

            modelBuilder.Entity("Econyx.Domain.Entities.Market", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(4000)
                        .HasColumnType("nvarchar(4000)");

                    b.Property<string>("ExternalId")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("Platform")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Question")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<DateTime?>("ResolutionDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("ResolvedOutcome")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<decimal>("Spread")
                        .HasPrecision(18, 6)
                        .HasColumnType("decimal(18,6)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("Version")
                        .HasColumnType("int");

                    b.Property<decimal>("VolumeUsd")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("Status");

                    b.HasIndex("ExternalId", "Platform")
                        .IsUnique();

                    b.ToTable("Markets", (string)null);
                });

            modelBuilder.Entity("Econyx.Domain.Entities.Order", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("FilledAt")
                        .HasColumnType("datetime2");

                    b.Property<decimal?>("FilledQuantity")
                        .HasPrecision(18, 6)
                        .HasColumnType("decimal(18,6)");

                    b.Property<Guid>("MarketId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Mode")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Platform")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("PlatformOrderId")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<decimal>("Quantity")
                        .HasPrecision(18, 6)
                        .HasColumnType("decimal(18,6)");

                    b.Property<string>("RejectionReason")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("Side")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("MarketId");

                    b.HasIndex("Status");

                    b.ToTable("Orders", (string)null);
                });

            modelBuilder.Entity("Econyx.Domain.Entities.Position", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("ClosedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsOpen")
                        .HasColumnType("bit");

                    b.Property<Guid>("MarketId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("MarketQuestion")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("Platform")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<decimal>("Quantity")
                        .HasPrecision(18, 6)
                        .HasColumnType("decimal(18,6)");

                    b.Property<string>("Side")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("StrategyName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("Version")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("IsOpen");

                    b.HasIndex("MarketId");

                    b.ToTable("Positions", (string)null);
                });

            modelBuilder.Entity("Econyx.Domain.Entities.Trade", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("ClosedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<TimeSpan>("Duration")
                        .HasColumnType("time");

                    b.Property<Guid>("MarketId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("MarketQuestion")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("Platform")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<Guid>("PositionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("Quantity")
                        .HasPrecision(18, 6)
                        .HasColumnType("decimal(18,6)");

                    b.Property<string>("Side")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("StrategyName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("ClosedAt");

                    b.HasIndex("MarketId");

                    b.ToTable("Trades", (string)null);
                });

            modelBuilder.Entity("Econyx.Domain.Entities.BalanceSnapshot", b =>
                {
                    b.OwnsOne("Econyx.Domain.ValueObjects.Money", "ApiCosts", b1 =>
                        {
                            b1.Property<Guid>("BalanceSnapshotId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<decimal>("Amount")
                                .HasPrecision(18, 6)
                                .HasColumnType("decimal(18,6)")
                                .HasColumnName("ApiCostsAmount");

                            b1.Property<string>("Currency")
                                .IsRequired()
                                .HasMaxLength(10)
                                .HasColumnType("nvarchar(10)")
                                .HasColumnName("ApiCostsCurrency");

                            b1.HasKey("BalanceSnapshotId");

                            b1.ToTable("BalanceSnapshots");

                            b1.WithOwner()
                                .HasForeignKey("BalanceSnapshotId");
                        });

                    b.OwnsOne("Econyx.Domain.ValueObjects.Money", "Balance", b1 =>
                        {
                            b1.Property<Guid>("BalanceSnapshotId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<decimal>("Amount")
                                .HasPrecision(18, 6)
                                .HasColumnType("decimal(18,6)")
                                .HasColumnName("BalanceAmount");

                            b1.Property<string>("Currency")
                                .IsRequired()
                                .HasMaxLength(10)
                                .HasColumnType("nvarchar(10)")
                                .HasColumnName("BalanceCurrency");

                            b1.HasKey("BalanceSnapshotId");

                            b1.ToTable("BalanceSnapshots");

                            b1.WithOwner()
                                .HasForeignKey("BalanceSnapshotId");
                        });

                    b.OwnsOne("Econyx.Domain.ValueObjects.Money", "TotalPnL", b1 =>
                        {
                            b1.Property<Guid>("BalanceSnapshotId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<decimal>("Amount")
                                .HasPrecision(18, 6)
                                .HasColumnType("decimal(18,6)")
                                .HasColumnName("TotalPnLAmount");

                            b1.Property<string>("Currency")
                                .IsRequired()
                                .HasMaxLength(10)
                                .HasColumnType("nvarchar(10)")
                                .HasColumnName("TotalPnLCurrency");

                            b1.HasKey("BalanceSnapshotId");

                            b1.ToTable("BalanceSnapshots");

                            b1.WithOwner()
                                .HasForeignKey("BalanceSnapshotId");
                        });

                    b.Navigation("ApiCosts")
                        .IsRequired();

                    b.Navigation("Balance")
                        .IsRequired();

                    b.Navigation("TotalPnL")
                        .IsRequired();
                });

            modelBuilder.Entity("Econyx.Domain.Entities.Market", b =>
                {
                    b.OwnsMany("Econyx.Domain.ValueObjects.MarketOutcome", "Outcomes", b1 =>
                        {
                            b1.Property<Guid>("MarketId");

                            b1.Property<int>("__synthesizedOrdinal")
                                .ValueGeneratedOnAddOrUpdate();

                            b1.Property<string>("Name")
                                .IsRequired()
                                .HasMaxLength(500);

                            b1.HasKey("MarketId", "__synthesizedOrdinal");

                            b1.ToTable("Markets");

                            b1
                                .ToJson("Outcomes")
                                .HasColumnType("nvarchar(max)");

                            b1.WithOwner()
                                .HasForeignKey("MarketId");

                            b1.OwnsOne("Econyx.Domain.ValueObjects.Probability", "Price", b2 =>
                                {
                                    b2.Property<Guid>("MarketOutcomeMarketId");

                                    b2.Property<int>("MarketOutcome__synthesizedOrdinal");

                                    b2.Property<decimal>("Value")
                                        .HasJsonPropertyName("price");

                                    b2.HasKey("MarketOutcomeMarketId", "MarketOutcome__synthesizedOrdinal");

                                    b2.ToTable("Markets");

                                    b2.WithOwner()
                                        .HasForeignKey("MarketOutcomeMarketId", "MarketOutcome__synthesizedOrdinal");
                                });

                            b1.OwnsOne("Econyx.Domain.ValueObjects.TokenId", "Token", b2 =>
                                {
                                    b2.Property<Guid>("MarketOutcomeMarketId");

                                    b2.Property<int>("MarketOutcome__synthesizedOrdinal");

                                    b2.Property<string>("Value")
                                        .IsRequired()
                                        .HasMaxLength(256)
                                        .HasJsonPropertyName("tokenId");

                                    b2.HasKey("MarketOutcomeMarketId", "MarketOutcome__synthesizedOrdinal");

                                    b2.ToTable("Markets");

                                    b2.WithOwner()
                                        .HasForeignKey("MarketOutcomeMarketId", "MarketOutcome__synthesizedOrdinal");
                                });

                            b1.Navigation("Price")
                                .IsRequired();

                            b1.Navigation("Token")
                                .IsRequired();
                        });

                    b.Navigation("Outcomes");
                });

            modelBuilder.Entity("Econyx.Domain.Entities.Order", b =>
                {
                    b.OwnsOne("Econyx.Domain.ValueObjects.Money", "FilledPrice", b1 =>
                        {
                            b1.Property<Guid>("OrderId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<decimal>("Amount")
                                .HasPrecision(18, 6)
                                .HasColumnType("decimal(18,6)")
                                .HasColumnName("FilledPriceAmount");

                            b1.Property<string>("Currency")
                                .IsRequired()
                                .HasMaxLength(10)
                                .HasColumnType("nvarchar(10)")
                                .HasColumnName("FilledPriceCurrency");

                            b1.HasKey("OrderId");

                            b1.ToTable("Orders");

                            b1.WithOwner()
                                .HasForeignKey("OrderId");
                        });

                    b.OwnsOne("Econyx.Domain.ValueObjects.Money", "Price", b1 =>
                        {
                            b1.Property<Guid>("OrderId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<decimal>("Amount")
                                .HasPrecision(18, 6)
                                .HasColumnType("decimal(18,6)")
                                .HasColumnName("OrderPriceAmount");

                            b1.Property<string>("Currency")
                                .IsRequired()
                                .HasMaxLength(10)
                                .HasColumnType("nvarchar(10)")
                                .HasColumnName("OrderPriceCurrency");

                            b1.HasKey("OrderId");

                            b1.ToTable("Orders");

                            b1.WithOwner()
                                .HasForeignKey("OrderId");
                        });

                    b.Navigation("FilledPrice");

                    b.Navigation("Price")
                        .IsRequired();
                });

            modelBuilder.Entity("Econyx.Domain.Entities.Position", b =>
                {
                    b.OwnsOne("Econyx.Domain.ValueObjects.Money", "CurrentPrice", b1 =>
                        {
                            b1.Property<Guid>("PositionId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<decimal>("Amount")
                                .HasPrecision(18, 6)
                                .HasColumnType("decimal(18,6)")
                                .HasColumnName("CurrentPriceAmount");

                            b1.Property<string>("Currency")
                                .IsRequired()
                                .HasMaxLength(10)
                                .HasColumnType("nvarchar(10)")
                                .HasColumnName("CurrentPriceCurrency");

                            b1.HasKey("PositionId");

                            b1.ToTable("Positions");

                            b1.WithOwner()
                                .HasForeignKey("PositionId");
                        });

                    b.OwnsOne("Econyx.Domain.ValueObjects.Money", "EntryPrice", b1 =>
                        {
                            b1.Property<Guid>("PositionId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<decimal>("Amount")
                                .HasPrecision(18, 6)
                                .HasColumnType("decimal(18,6)")
                                .HasColumnName("EntryPriceAmount");

                            b1.Property<string>("Currency")
                                .IsRequired()
                                .HasMaxLength(10)
                                .HasColumnType("nvarchar(10)")
                                .HasColumnName("EntryPriceCurrency");

                            b1.HasKey("PositionId");

                            b1.ToTable("Positions");

                            b1.WithOwner()
                                .HasForeignKey("PositionId");
                        });

                    b.OwnsOne("Econyx.Domain.ValueObjects.Money", "ExitPrice", b1 =>
                        {
                            b1.Property<Guid>("PositionId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<decimal>("Amount")
                                .HasPrecision(18, 6)
                                .HasColumnType("decimal(18,6)")
                                .HasColumnName("ExitPriceAmount");

                            b1.Property<string>("Currency")
                                .IsRequired()
                                .HasMaxLength(10)
                                .HasColumnType("nvarchar(10)")
                                .HasColumnName("ExitPriceCurrency");

                            b1.HasKey("PositionId");

                            b1.ToTable("Positions");

                            b1.WithOwner()
                                .HasForeignKey("PositionId");
                        });

                    b.Navigation("CurrentPrice")
                        .IsRequired();

                    b.Navigation("EntryPrice")
                        .IsRequired();

                    b.Navigation("ExitPrice");
                });

            modelBuilder.Entity("Econyx.Domain.Entities.Trade", b =>
                {
                    b.OwnsOne("Econyx.Domain.ValueObjects.Money", "EntryPrice", b1 =>
                        {
                            b1.Property<Guid>("TradeId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<decimal>("Amount")
                                .HasPrecision(18, 6)
                                .HasColumnType("decimal(18,6)")
                                .HasColumnName("EntryAmount");

                            b1.Property<string>("Currency")
                                .IsRequired()
                                .HasMaxLength(10)
                                .HasColumnType("nvarchar(10)")
                                .HasColumnName("EntryCurrency");

                            b1.HasKey("TradeId");

                            b1.ToTable("Trades");

                            b1.WithOwner()
                                .HasForeignKey("TradeId");
                        });

                    b.OwnsOne("Econyx.Domain.ValueObjects.Money", "ExitPrice", b1 =>
                        {
                            b1.Property<Guid>("TradeId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<decimal>("Amount")
                                .HasPrecision(18, 6)
                                .HasColumnType("decimal(18,6)")
                                .HasColumnName("ExitAmount");

                            b1.Property<string>("Currency")
                                .IsRequired()
                                .HasMaxLength(10)
                                .HasColumnType("nvarchar(10)")
                                .HasColumnName("ExitCurrency");

                            b1.HasKey("TradeId");

                            b1.ToTable("Trades");

                            b1.WithOwner()
                                .HasForeignKey("TradeId");
                        });

                    b.OwnsOne("Econyx.Domain.ValueObjects.Money", "Fees", b1 =>
                        {
                            b1.Property<Guid>("TradeId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<decimal>("Amount")
                                .HasPrecision(18, 6)
                                .HasColumnType("decimal(18,6)")
                                .HasColumnName("FeeAmount");

                            b1.Property<string>("Currency")
                                .IsRequired()
                                .HasMaxLength(10)
                                .HasColumnType("nvarchar(10)")
                                .HasColumnName("FeeCurrency");

                            b1.HasKey("TradeId");

                            b1.ToTable("Trades");

                            b1.WithOwner()
                                .HasForeignKey("TradeId");
                        });

                    b.OwnsOne("Econyx.Domain.ValueObjects.Money", "PnL", b1 =>
                        {
                            b1.Property<Guid>("TradeId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<decimal>("Amount")
                                .HasPrecision(18, 6)
                                .HasColumnType("decimal(18,6)")
                                .HasColumnName("PnLAmount");

                            b1.Property<string>("Currency")
                                .IsRequired()
                                .HasMaxLength(10)
                                .HasColumnType("nvarchar(10)")
                                .HasColumnName("PnLCurrency");

                            b1.HasKey("TradeId");

                            b1.ToTable("Trades");

                            b1.WithOwner()
                                .HasForeignKey("TradeId");
                        });

                    b.Navigation("EntryPrice")
                        .IsRequired();

                    b.Navigation("ExitPrice")
                        .IsRequired();

                    b.Navigation("Fees")
                        .IsRequired();

                    b.Navigation("PnL")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
